language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    
install:
    - pip install -r requirements.travis.txt
    - pip install setup.py
    
script: 
    - pytest
    - pytest --doctest-modules