site_name: SimCADocs - Documentation for SimCADO
pages:
- Home: index.md
- Getting Started: GettingStarted.md
- Examples:
    - 'Controlling SimCADO': 'examples/UserCommands.md'
    - 'Creating Sources': 'examples/Source.md'
    - 'Manipulating the Optical Train': 'examples/OpticalTrain.md'
    - 'Reading out the Detector': 'examples/Detector.md'
- Download: Download.md
- SimCADO in depth: 
    - 'How SimCADO works': deep_stuff/SimCADO.md
    - 'Testing SimCADO': deep_stuff/Testing.md
    - 'FAQs': deep_stuff/FAQs.md
- List of Control Keywords: Keywords.md
- API Documentation: API.md
theme: readthedocs