site_name: SimCADocs - Documentation for SimCADO
pages:
- Home: index.md
- Getting Started: GettingStarted.md
- Examples:
    - 'Controlling SimCADO': 'examples/UserCommands.md'
    - 'Creating Sources': 'examples/Source.md'
    - 'Manipulating the Optical Train': 'examples/OpticalTrain.md'
    - 'Reading out the Detector': 'examples/Detector.md'
- Download: Download.md
- SimCADO FAQs: SimCADO.md
- API Documentation: API.md
theme: readthedocs